name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Azure 로그인
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4}}
          
      # 3. ACR에 로그인
      - name: Log in to Azure Container Registry
        run: |
          az acr network-rule add --resource-group webapp-rg --name acrkoo --ip-address ${{ steps.ip.outputs.ipv4}}
          az acr login --name ${{ secrets.ACR_NAME }}



      # 4. (선택) 이미지 최신 태그 업데이트
      - name: Update 'latest' tag
        run: |
          
          docker pull ubuntu:24.04
          docker tag ubuntu:24.04 ${{ secrets.ACR_NAME }}.azurecr.io/ubuntu:1.0
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest

          az acr network-rule remove --resource-group webapp-rg --name acrkoo --ip-address ${{ steps.ip.outputs.ipv4}}

          echo "done"
          
